authors:
  GentleTomZerg:
    name: Tom
    description: Creator
    # Use github avatar link
    avatar: https://avatars.githubusercontent.com/u/51043088?s=400&u=e233a4511c1fc3a60a8afcc9b5a18839c3a1bb9e&v=4
